- name: Job tag sample
  hosts: all
  tasks:
    - block:

      - name: Hello Message
        debug:
          msg: "Hello World!"
        tags: tag-1

      - name: Display multiple file contents
        ansible.builtin.debug: var=item
        with_file:
          - "/var/run/secrets/kubernetes.io/serviceaccount"

      - name: Check gitops namespace
        kubernetes.core.k8s:
          state: present
          api_version: v1
          kind: Namespace
          name: "openshift-config"

      module_defaults:
        group/kubernetes.core.k8s:
          validate_certs: false

